###################################################
#       force control
###################################################
main_loop_rate: 500

# controller
Transform: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
force_controlled_dimensions: 3

# Admittance control parameters
# For each axis
#   k: stiffness
#   m: mass (kg)
#   alpha: viscous friction
# TODO(yifan) we need to be able to set these online
AC_para_X: # first axis (if the axes are rotated)
  k: 0
  m: 2
  alpha: 1500
AC_para_Y: # second axis (if the axes are rotated)
  k: 0
  m: 3
  alpha: 1500
AC_para_Z: # third axis (if the axes are rotated)
  k: 0
  m: 3
  alpha: 300
AC_limit: 300.0 # (mm) magnitude limit of output  THIS WILL CREATE A BOUNDING BOX

# Force control PID Gains
FC_gains:
  IGain: 0.01 # 0.02
  PGain: 0.0 #0.4
  DGain: 0.00 #0.02
FC_I_Limit: 20 # 50 Newton

forcecontrol_print_flag: true
forcecontrol_file_path: "/home/yifanh/Git/catkin_ws/src/forcecontrol/data/forcecontrol_data.txt"

###################################################
#       robot_bridge
###################################################
robot_bridge:
    default_pose: # when tool frame is set for probe
      x: 50 #40
      y: 416
      z: 378
      qw: 0
      qx: 0.55187
      qy: -0.83393
      qz: 0